nelmio_cors:
  paths:
    "^/api/": # Assurez-vous que le chemin correspond à vos routes API
      allow_origin: ["*"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
