# config/services.yaml

parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Explicitly configuring the Security service is not necessary as it's autowired by Symfony
  # Symfony\Component\Security\Core\Security: ~

  # Doctrine\ORM\EntityManagerInterface is automatically handled by DoctrineBundle
